### ISSUE TITLE
Integrating live chat in a Single page application 

### ISSUE THREAD

**Issue by eranotz50** [livechat/api-client-nodejs#3]
I came across an issue which does not make much sense to me as a developer and i'm hoping i got it wrong.

1) The only way i can open a chat window with a specific group is to set the group id before loading the chat window script. 
If i don't do it like that i get the default group , Is this assumption correct ? I was not able to do it in any other way. 

```
     function loadChatScript(groupId) {

              window.__lc.group = groupId;

              var lc = document.createElement('script');
              lc.type = 'text/javascript';
              lc.async = true;
              lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
              var s = document.getElementsByTagName('script')[0];
              s.parentNode.insertBefore(lc, s);
    }
```

**Comment by bolchowka** [comment]
Hi Eran,
we have simplified choosing groups since node.js library was created. You can set up groups based on the URL of your app, which is especially useful for single page applications. No no longer need to set groups in the installation code.

Read more here: https://www.livechatinc.com/kb/setting-up-url-rules-for-groups/

Hope it helps!

**Comment by eranotz50** [comment]
O'k that's good to know i actually thought this could lead me to how this could be done using the installation code and just gave a scenario which would be easy the explain.  (The scenario of an SPA app) .

Here's what i really need. 
I Have 3 scenarios : 

1) Open a chat with any agent available ( this i know you support ) 
2) Open a chat with a specific agent. Which i already implement by assigning a 1:1 agent < - > group relationship, and then setting the group id corresponding to that agent. 
3) If that specific agent is offline i would transfer it to another specific agent ?

Questions : 

```
1) How would you implement these scenarios ?
2) Is there a built in way of assigning routing rule between groups ? 
```

##    Nice to have: 

   *\* 3) A thing that scares me in regards to future flexibilty is that once you loaded the installation script it does not seem possible to chat with a different agent them the one you spoke with before. 
     I have a scenario where users logout and then login with a different account with out refreshing the page. Iv'e noticed that you keep a session and always return to the same agent ( even if he is offline i still got the same one...)

**Comment by bolchowka** [comment]
Scenarios 1) and 2) should be implemented exactly as you did that (URL rules + separate group for each agent).
Scenario 3) can be implemented by adding a "group selection" dropdown in the pre-chat survey. This way, your client will see which groups (from scenario 2) are online, which are offline, and he/she will be able to pick the one that is online.

Routing to the same agent is our built-in feature, but it can be modified on our side. Please reach out to our support team (available 24/7 via chat on www.livechatinc.com) and ask them to help you with that.
